"""2

Revision ID: 8592054ed721
Revises: b005b0730015
Create Date: 2023-04-27 01:14:28.559439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8592054ed721'
down_revision = 'b005b0730015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_issuance_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('authors', sa.String(length=255), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('edition', sa.String(length=255), nullable=True),
    sa.Column('isbn', sa.String(length=255), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('issuance_date', sa.DateTime(), nullable=True),
    sa.Column('actual_return_date', sa.DateTime(), nullable=True),
    sa.Column('returnstatus', sa.Enum('RETURNED', 'PENDING_RETURN', name='returnstatus'), nullable=True),
    sa.Column('entry_created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('entry_updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book_issuance_tracker', schema=None) as batch_op:
        batch_op.alter_column('returnstatus',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Enum('RETURNED', 'PENDING_RETURN', name='returnstatus'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_issuance_tracker', schema=None) as batch_op:
        batch_op.alter_column('returnstatus',
               existing_type=sa.Enum('RETURNED', 'PENDING_RETURN', name='returnstatus'),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)

    op.drop_table('book_issuance_history')
    # ### end Alembic commands ###
