"""init

Revision ID: 88fac50d844c
Revises: 
Create Date: 2023-04-24 02:15:13.216528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88fac50d844c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('authors', sa.String(length=255), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('edition', sa.String(length=255), nullable=True),
    sa.Column('isbn', sa.String(length=255), nullable=True),
    sa.Column('shelfnum', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('totalnoofcopies', sa.Integer(), nullable=True),
    sa.Column('availablenoofcopies', sa.Integer(), nullable=True),
    sa.Column('entry_created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('book_issuance_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book', sa.Integer(), nullable=True),
    sa.Column('issued_to', sa.Integer(), nullable=True),
    sa.Column('issuance_date', sa.DateTime(), nullable=True),
    sa.Column('to_be_returned_by_date', sa.DateTime(), nullable=True),
    sa.Column('actual_return_date', sa.DateTime(), nullable=True),
    sa.Column('returnstatus', sa.Enum('RETURNED', 'YETTOBERETRUNED', name='returnstatus'), nullable=True),
    sa.Column('entry_created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('entry_updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book'], ['book.id'], ),
    sa.ForeignKeyConstraint(['issued_to'], ['user.userid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_issuance_tracker')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('book')
    # ### end Alembic commands ###
